### ISSUE TITLE
Modal background not long enough

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/learn#55]
The curriculum map modal background does not continue to the bottom of a long list. See below.
![fcc2-modal](https://user-images.githubusercontent.com/1513130/40250936-d6b8912c-5aa5-11e8-8b25-4c264ba07036.gif)

**Comment by Bouncey** [comment]
Hi @beaucarnes, can you try a hard refresh of the page. We have service workers on the site and you might be working off an old version. We fixed this in #50

Please let me know how you get on

**Comment by beaucarnes** [comment]
Not fixed.
![fcc5](https://user-images.githubusercontent.com/1513130/40255145-1a158052-5ab4-11e8-98f5-2e94a726b9fd.gif)

**Comment by beaucarnes** [comment]
Fixed now that I'm testing on the correct url!
